Update installation.md
ReactionMechanismGenerator/T3 pull request #94
Opened 2023-01-03 15:36 UTC by Laxzal

Hey Alon, please check out the changes I have made to the installation instructions and see if they make sense to you

2023-01-03 18:20 UTC, alongd commented
@Laxzal, yes - looks good

Do we say anywhere that they need to also have RMG and ARC installed?

BTW, the PR should be merged into `main`, not `master`. Perhaps we could deleted `master` to avoid confusion?

2023-01-09 09:57 UTC, Lilachn91 requested changes

2023-01-09 09:57 UTC, Lilachn91 commented on docs/installation.md
> +T3 requires RMG-Py, RMG-databse and ARC to function correctly. In order install the necessary dependencies, you can follow either option below.<br>
fix the English (add to after in order)

2023-01-09 09:57 UTC, Lilachn91 commented on docs/installation.md
> +### Option 2:
Add arc installation instructions

2023-01-09 10:13 UTC, Lilachn91 approved these changes
Looks good!

2023-01-09 11:20 UTC, merged